--- #YAML:1.0
name:               Template-Plugin-MultiMarkdown
version:            0.03
abstract:           TT plugin for Text::MultiMarkdown
author:
    - Andrew Ford <A.Ford@ford-mason.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Template:             2.16
    Text::Markdown:       0
    Text::MultiMarkdown:  1.0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
