---
abstract: 'TT plugin for Text::MultiMarkdown'
author:
  - 'Andrew Ford <andrew@ford-mason.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-MultiMarkdown
no_index:
  directory:
    - t
    - inc
requires:
  Template: 2.16
  Text::MultiMarkdown: v1.0.1
  parent: 0
version: 0.06
