--- #YAML:1.0
name:                     Template-Plugin-MultiMarkdown
version:                  0.06
abstract:                 TT plugin for Text::MultiMarkdown
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site
dynamic_config:           1

build_requires:
  ExtUtils::MakeMaker:      0
configure_requires:
  ExtUtils::MakeMaker:      0
requires:
  perl:                     5.006
  parent:                   0
  Template:                 2.16
  Template::Plugin::Filter: 2.16
  Text::MultiMarkdown:      v1.0.1
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  Template::Plugin::Digest::SHA1:
    file:     lib/Template/Plugin/Digest/SHA1.pm
    version:  0.04
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Digest-SHA1
  repository: http://github.com/barbie/template-plugin-digest-sha1

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
